name: 'gps_analysis'
version: '1.0.0'
config-version: 2

profile: 'gps_analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  gps_analysis: 
    +materialized: view
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral # Intermediate models won't be created in the database
    marts:
      +materialized: table # Mart models will be created as tables for performance