
version: 2

models:
  - name: stg_geolife__activities
    description: "geolife gps data, renamed columns"
    columns:
      - name: activity_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null